### ISSUE TITLE
Feature request: Move ValueSpecification Instance Editor To Shared location for studio/query to leverage

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#1173]
### Similar requests

- [X] I have searched and found no existing similar requests

### What problems are you trying to solve?

We need to leverage the value specification in different areas of studio such as:
- parameter editors in service execution, service test
- EqualTo Test Assertion Could leverage the value specification editor

### Describe the solution you would like to see implemented

Add new package `legend-graph-shared-components` which would hold shared graph editors

### Describe alternatives you have considered

We would consider instead to leverage the new ValueSpecification APIS in legend engine and instead provide users an input similar to LambdaEditors when editing ValueSpecification values. 
@akphi  what do you think? 

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment]
@MauricioUyaguari Basically, we're moving `QueryBuilderValueSpecificationEditor` out. We put in some huge effort in `5.0.0` to make sure this component does not really depend on any logic of query builder, but more just basing off `ValueSpecification`. That's one step easier for us.

However, the logic of dealing with `ValueSpecification` transformation might be a little too tightly-bound to query builder, since the latter understands how to dissect certain functions such as `today()`, `now()`, etc. So I'm suggesting before creating a module like `@finos/legend-graph-shared-components`, we need to consider how to untangle just the logic bit needed for `basic value spec editor` out of `@finos/legend-query`. If we can't find a satisfactory way, we should just make the value spec editor a plugin to `@finos/legend-studio` and expose it via `@finos/legend-studio-plugin-query-builder`. 

> Remember, conceptually this is sensible still because when we created `@finos/legend-query`, we intend to have this module understand everything about `Value Specification`, `@finos/legend-graph` doesn't handle function-matching, type-matching, etc.
