### ISSUE TITLE
User ID data is missing error upon installation

### ISSUE THREAD

**Issue by jonnance** [finos/legend-studio#28]
Hi, 

I have gone through the steps to install and run legend-studio on my computer (windows) by following the readme (npm install, npm run setup, npm start). Upon running npm start, my browser opens https://localhost:3000/studio, however I get an error on the screen that reads "Assertion Error: User ID data is missing". 

Is there a file that I should use to configure a default user ID or should I have installed a separate legend component (I only installed studio)?

<img width="322" alt="Screenshot 2020-10-28 152101" src="https://user-images.githubusercontent.com/29903157/97486068-554af600-1931-11eb-9215-baec2a10eba8.png">

**Comment by jean-col** [comment]
I am having the same issu that comes from the ApplicationConfig.ts, which needs to the SDLC server. So you need to run the engine and the sdlc servers. 

I am running both engines and used the default configurations and eventually changed the default URLs (/sdlc and /exec in the config.ts file to the local host url) but to no avail. 

As I exercise some of the APIs in the Swagger url for engine and sdlc, when I try and get current user it fails trying to access gitlab ... The install doc for studio requires an application to be created in one's gitlab account but without giving details on how to create that application. 

Can anyone provide more detail on all this?

**Comment by akphi** [comment]
@jonnance As @jean-col mentioned, this is caused by the fact that we call SDLC server on start. We are making change to make this more non-mandatory, but regardless, you need both servers to be on (execution server is relatively easy to manage, but SDLC server begs for a Gitlab instance). Admittedly, the current setup is not too user-friendly and we're working on it as well.

If you have access to https://legend.finos.org/studio I believe you can point your SDLC and EXEC server to https://legend.finos.org/sdlc and https://legend.finos.org/exec respectively

Really sorry for the inconvenience, hopefully we can push another change to make this less painful.

**Comment by gs-bracej** [comment]
Thanks @akphi, this is the best thing to do. 

@jonnance ss long as you have an account on the FINOS instance, you can edit the dev/config/config.json and change the sdlcServer and execServer options to https://legend.finos.org/sdlc and https://legend.finos.org/exec respectively. Please let us know how it goes!

**Comment by jonnance** [comment]
Can you check if this is the right way editing the config.json? 

`{
  "realm": "test-env",
  "sdlcServer": "https://legend.finos.org/sdlc",
  "execServer": "https://legend.finos.org/exec",
  "tracerServer": "/tracer",
  "documentation": {
    "fullDocUrl": "https://legend.finos.org/docs/getting-started/installation-guide"
  },
  "features": []
}`

Still getting the same error. Here are a few details I get when I look at the request that the browser makes
![image](https://user-images.githubusercontent.com/29903157/99577651-a9ce1800-29a9-11eb-974b-deff3139a49d.png)

**Comment by gs-bracej** [comment]
You might need to log into https://legend.finos.org/studio to create your access token first.

**Comment by jonnance** [comment]
I'm logged in to legend.finos.org/studio and if I go directly to https://legend.finos.org/exec/api/server/v1/currentUser, it does correctly resolve my user name. Should I be adding a particular type of access token in gitlab? (https://gitlab.legend.finos.org/)

Otherwise I already have an application registered in gitlab under the name Legend with the scopes openid, profile and api

**Comment by gs-bracej** [comment]
Hm that's very strange! Are you saying that accessing that URL directly doesn't work, but if it's called from your local Studio it doesnt?

**Comment by jonnance** [comment]
May be a typo in your response - accessing the URL directly does work, but if it is called from my local studio then it does not work

**Comment by gs-bracej** [comment]
Apologies, you correctly worked out my meaning despite the confusing reponse :)
Thanks for confirmation - will try to repo and loop back with you.

**Comment by jonnance** [comment]
Hi - just checking if you were able to reproduce the issue. Let me know if I should change something in my configuration.

**Comment by akphi** [comment]
@gs-bracej @jonnance I just tried to set this up to point at my local engine and remote SDLC server (i.e. https://legend.finos.org/sdlc) and it seems like I get `401` for the call to check for authorization (i.e. https://legend.finos.org/sdlc/auth/authorized)

This works fine on Firefox though, we need to investigate a bit here, probably something to do with CORS

**Comment by gs-bracej** [comment]
Ah, I see the problem! It's a simple enough issue with CORS, the current headers don't allow Chrome to send Cookies so the user isn't authenticated. I'm surprised it works with Firefox, I guess they don't fully support CORS.

Will get a fix committed and loop back.

**Comment by gs-bracej** [comment]
An update on this: This is actually caused by the change in behaviour for Chromium-based browsers with regards to third-party cookies. Details are here - https://www.chromium.org/updates/same-site
This also explains why Firefox is unaffected. 

Long-term we'll need to update Legend Engine and SDLC servers to send the magic new params on the cookies, but this needs quite extensive changes which will take time.

In the immediate term, there are two workarounds:
1. Use a non Chromium-based browser, eg Firefox
2. Disable the new SameSite behaviour by setting the following two browser flags to Disabled:
chrome://flags/#same-site-by-default-cookies
chrome://flags/#cookies-without-same-site-must-be-secure

**Comment by akphi** [comment]
@gs-bracej how extensive you think this change could be, is this about updating `legend-shared` to append `; SameSite=None` to its cookies like `LegendSSO`. Or is the problem is related to other members of the list like `JSESSIONID`? I put a screenshot here of what I see I have, but not sure which one we really need to care about.

<img width="1240" alt="legend-studio-cookie" src="https://user-images.githubusercontent.com/13574879/110225458-bf614200-7eb3-11eb-9a71-67c9d1cc847b.png">

@kevin-m-knight-gs I saw SDLC have also sent its own cookies like LegendSDLCSession. Is there anything else that we need to care about if we are to tackle this fix?

**Comment by akphi** [comment]
Looks like Firefox will soon follow Chrome and ban cross-site cookies. I saw this in Firefox@86
```
Cookie “LegendSSO” will be soon treated as cross-site cookie against “https://127.0.0.1:3000/studio” because the scheme does not match.
```

**Comment by aamend** [comment]
I confirm I'm facing the same issue using both Chrome and Firefox. Please note that I'm running my own SDLC and engine. The chrome://flags workaround does not seem to change anything. 

Tested on
`git checkout tags/legend-studio-0.1.0`
`git checkout tags/legend-studio-0.1.1`

The issue is slightly different on `git checkout master` as the page simply hangs with an "unauthorized" popup. 

Is there any known workaround?

**Comment by akphi** [comment]
@kevin-m-knight-gs mentioned that `SameSite=None` needs to be [set together with `Secure`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#samesitenone_requires_secure). This means we might need to make all of our infra running on HTTPS, or am I wrong here @epsstan ?

**Comment by akphi** [comment]
@jonnance I believe you can try this once again; since then we have improved our doc a lot for starting up Studio. You can see there are a few options now.
- Using `Maven`: https://legend.finos.org/docs/installation/maven-install-guide
- Using `docker-compose`: https://github.com/finos/legend/tree/master/installers/docker-compose

Half way through we have sidetracked to the conversation regarding `SameSite` attribute of cookie, but I suppose we can re-open another issue on `finos/legend` when the need comes up again. I will close this issue for now.
