### ISSUE TITLE
Bug: Support Integers as Enum Values

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#563]
## 🐛 Bug Report

When a user defines an Enumeration with an Enum value that is of integers, it fails when parsing the grammar in text mode. 

```
Enum model::Something {
  1,
  1A
  // both of the above example will fail
}
```

### Step to Reproduce

Steps to reproduce the behaviour:

- Create an Enumeration with an Enum of Integer in form mode
- Switch to text mode. You will get a token error as the grammar is not parsable

### Possible Solution
Most likely a `BACKEND` fix. We may want to allow integers in the grammar? or add a single quote to integers that come in from protocol.

**Comment by akphi** [comment]
@YannanGao-gs @MauricioUyaguari as discussed, we would mark this one as a `Won't fix`, could you draft what we learnt from our investigation @YannanGao-gs ?

**Comment by YannanGao-gs** [comment]
Close this ticket due to the reasons below.
1. Able to create an enum whose values are Integer, but this kind of enum can not be referenced. e.g. `myEnum.1`
    When parsing the code `myEnum.1`, `.1` will be treated as a Float since Float/Decimal has a higher priority than our customed token. Therefore, there will be an 'unexpected token' error when referring to this kind of enum.
2. Able to create an enum whose values are single-quoted Integer,  but single quotes will be removed during the roundtrip.
`Enum model::Something {'1'} `. -> `Enum model::Something {1} `
    There is a special logic to get rid of the single quote as long as it matches a regex pattern.

**Comment by akphi** [comment]
Just to add on to @YannanGao-gs very well-written explanation above:

1. This in fact affects identifiers starting with a number in general, e.g. `1`, `1A`, due to the problem described, `.1` will always be tokenized as a float.

2. We have this handling of `quoted identifier` where `'1'` will get interpreted as `1` and the quotes are removed in the protocol model when the grammar is parsed. Now in the composer, we have a logic where if the identifier value matches a generic pattern, no quotes would be added around the string. If we want to support this feature, we need to hack that rule a bit. The question remains how hacky we want to get this done. Also, is `enum value` the only case or should we also support `class property` for that matter?

We will close this here until this another solution comes to light for this.
